# Generated by Django 3.2.5 on 2021-07-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20210719_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='mailing_address',
            field=models.BooleanField(null=True),
        ),
    ]
