# Generated by Django 3.2.5 on 2021-07-19 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20210719_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='state',
        ),
        migrations.CreateModel(
            name='MoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('Married', 'married'), ('Unmarried', 'unmarried'), ('Separated', 'separated')], max_length=10, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(choices=[('Karnataka', 'karnataka'), ('Maharashtra', 'maharashtra'), ('New York', 'new york'), ('Texas', 'texas'), ('Melbourne', 'melbourne')], max_length=30, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message="Pin number must be entered in the format: '99999'. Up to 6 digits allowed.", regex='^\\d{6,6}$')])),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Australia', 'Australia')], max_length=30, null=True)),
                ('mailing_address', models.BooleanField(null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Aadhar number must be entered in the format: '1111 1111 1111 1111'. Up to 12 digits allowed.", regex='^\\d{12,12}$')])),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Pan number must be entered in the format: 'AhsGr2783d'. Up to 10 digits allowed.", regex='^[A-Za-z]{5}\\d{4}[A-Za-z]{1}$')])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.personaldetails')),
            ],
        ),
    ]
