# Generated by Django 3.2.5 on 2021-07-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20210719_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='moredetails',
            name='b_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='details.dependantdetails'),
        ),
        migrations.AddField(
            model_name='moredetails',
            name='cb_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='details.coborrowerdetails'),
        ),
    ]
