# Generated by Django 3.2.5 on 2021-07-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brands', models.CharField(choices=[('HONDA', 'honda'), ('HYUNDAI', 'hyundai'), ('MERCEDES', 'mercedes'), ('FORD', 'ford')], max_length=50)),
                ('car_models', models.CharField(choices=[('CIVIC', 'civic'), ('I10', 'i10'), ('C-Class', 'c-class'), ('FIGO', 'figo')], max_length=50)),
                ('purchase_price', models.BigIntegerField()),
                ('down_payment', models.IntegerField(max_length=2)),
                ('desired_loan', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ANDHRA PRADESH', 'andhra pradesh'), ('KARNATAKA', 'karnataka'), ('MAHARASHTRA', 'maharashtra'), ('RAJASTHAN', 'rajasthan')], max_length=50)),
                ('city', models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Jaipur', 'Jaipur')], max_length=50)),
                ('purchase_price', models.BigIntegerField()),
                ('down_payment', models.IntegerField(max_length=2)),
                ('desired_loan', models.BigIntegerField()),
            ],
        ),
    ]
