# Generated by Django 3.2.5 on 2021-07-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20210719_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='desired_loan',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='down_payment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='purchase_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.state')),
            ],
        ),
        migrations.CreateModel(
            name='Car_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.car_brands')),
            ],
        ),
        migrations.AlterField(
            model_name='carloan',
            name='car_brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.car_brands'),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='car_models',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.car_models'),
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.city'),
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.state'),
        ),
    ]
